// <auto-generated />
namespace SchoolDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StudentNameSetRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentNameSetRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201711151622185_StudentNameSetRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
